### ISSUE TITLE
URL Parameter

### ISSUE THREAD

**Issue by bossinc** [bossinc/ATUDegreePlanner#1]

**Comment by XintongRen** [comment]
I find some info about Getting URL parameters & values with jQuery  http://jquery-howto.blogspot.com/2009/09/get-url-parameters-values-with-jquery.html  

this guy is Generate URL-encoded query string use the function "http_build_query"
http://php.net/manual/en/function.http-build-query.php  (will study more about this later)

Separators!!
http://docs.frevvo.com/d/display/frevvo62/URL+Parameters
arg_separator
arg_separator.output is used to separate arguments, unless this parameter is specified, and is then used.

**Comment by bossinc** [comment]
Complete
